AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance

Parameters:
 MyKeyName:
   Description: Select the keyName from List
   Type: AWS::EC2::KeyPair::KeyName
 MyAvailabilityZone:
   Description: Select Availability Zone
   Type: String
   Default: us-east-2a
   AllowedValues:
    - us-east-2a
    - us-east-2b
    - us-east-2c
 MyInstanceType:
    Description: Select the instancetype from the SSM
    Type: AWS::SSM::Parameter::Value<String>
      
Resources:
  DevEC2Insatnce:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0998bf58313ab53da
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      AvailabilityZone: !Ref MyAvailabilityZone
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new ssh sg
      SecurityGroupIngress:
       -  IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
       -  IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0  
  MyElastciIp:
     Type: AWS::EC2::EIP
     Properties:
      InstanceId: !Ref DevEC2Insatnce         

     